### ISSUE TITLE
Gamut Compress 0.7 issue with W10/DR17/ATI

### ISSUE THREAD

**Issue by ConnecTEDDD** [jedypod/gamut-compress#4]
Thank you in advance for your work.

The latest version of 0.7 is not working in Windows 10 with Resolve 17 (17.1.1 Build 9) and ATI Radeon VII.

All previous releases are currently working to my system: 0.6 / 0.5 / 0.36 / 0.35 / 0.3.

Thank you.

Ted.

**Comment by nick-shaw** [comment]
Resolve 17 is more picky about DCTL syntax than 16 was. The UI parameter lines at the top should not end with semicolons (my mistake when I first wrote the DCTL version). Also some GPU architectures accept `float3 rgb = make_float3(0.0f)`, but this is not strictly correct DCTL. Three float values should be passed, and the above code will fail on some systems. Making these corrections to the DCTL should make it run on all Resolve 17 systems.

**Comment by ConnecTEDDD** [comment]
Hi Nick,

Thank you for your helpful input.

After changing:

float3 d = ac == 0.0f ? make_float3(0.0f) : (ac-rgb)/_fabs(ac);

to

float3 d = ac == 0.0f ? make_float3(0.0f, 0.0f, 0.0f) : (ac-rgb)/_fabs(ac);

...It's working now. :)

With or without semicolons to the UI parameters lines is not affecting the operation, at least to the only system I have to check.

Thank you.

**Comment by jedypod** [comment]
Thanks to @nick-shaw's pull request this should be fixed now! Thanks for the flag, @ConnecTEDDD and don't hestitate if you see any other problems.
