### ISSUE TITLE
CalculateDistance swapped coeffs for Rec709?

### ISSUE THREAD

**Issue by Dogway** [jedypod/gamut-compress#7]
I'm not sure if this is a Rec709 only thing or not, but if I were to use your coefficients for any sample (ie. blue bar exr) blues skew to purple. I noticed this issue while working on an implementation in AviSynth.

The Nuke set up is a bit confusing but since you don't have an expressive code block to reference to I will post my implementation.

You seem to extract max() from columns in row-major order for the distance ratio matrix, while probably extracting rows is expected:

Max() for columns, yields `[0.518208,0.074934,0.088542]` for Rec709 from Rec2020:
```
max(DRat[0],DRat[3],DRat[6])
max(DRat[1],DRat[4],DRat[7])
max(DRat[2],DRat[5],DRat[8])
```

Max() for rows, yields `[0.074934,0.518208,0.063425]` for Rec709 from Rec2020:
```
max(DRat[0],DRat[1],DRat[2])
max(DRat[3],DRat[4],DRat[5])
max(DRat[6],DRat[7],DRat[8])
```

Another thing I implemented is distance aware thresholds, so the rolloff is equivalent for all the channels. If distance is short, you can get away with a lower threshold and hence keep more of the saturation. My function fit is: `0.085*log10(Dist+0.0036)+0.208`

With that said I'm aware this is a workaround and the Path to White is skewed as this method only aligns primaries, so I still see, specially in red a big hue shift to oranges. This is not apparent with ACES ODTs because of its 'red glow' artifact though.

EDIT: By the way, I saw conflicting coefficients. In this [post](https://community.acescentral.com/t/rgb-saturation-gamut-mapping-approach-and-a-comp-vfx-perspective/2715/88) you recommended for ACEScg from AlexaWG `[0.075553775,0.218766689,0.052656531]` while in your current blink [file](https://github.com/jedypod/gamut-compress/blob/18c979252faacaf144f86cdb62c0ee3d303bf6f5/GamutCompress_blink.nk#LL12C1-L12C18) you recommend `[0.078,0.22,0.056]`. With row max() I get `[-0.007,0.0582,0.211105]` including chromatic adaptation.

EDIT2: I noticed you didn't attach a license. Am I ok to port this to AviSynth+ or should I add a license disclaimer? Thanks!

**Comment by jedypod** [comment]
Hey @Dogway ,
Super sorry I missed this until now. Hopefully my reply is not too late to be useful.

First, yeah feel free to port this to AviSynth. I have not licensed this code, but it was taken by AMPAS as the ACES "Reference Gamut Compression" [here](https://github.com/ampas/aces-vwg-gamut-mapping-2020) and is there licensed permissively.

I'll try to clear up some of the confusion about the distance limits:
1. This algorithm distorts hue paths as it compresses.
2. The direction of the distortion is modified by the threshold and limit controls of each channel.
3. I would treat the compression controls more as a creative grading tool than a scientism exercise: You won't gain much by perfectly fitting the distances to some source camera gamut.
4. Hue appearance depends on the view transform you are using downstream, and also what gamut this compression is applied in.

Hope that helps.

**Comment by Dogway** [comment]
Thanks for the reply! No prob.

I pro-actively implemented it for AviSynth [here](https://github.com/Dogway/Avisynth-Scripts/blob/aebb92df33fc912d4ee78000c6db34704d1fc995/TransformsPack%20-%20Models.avsi#L1979). Instead of the RGC I implemented your version as per your guidance [referenced](https://github.com/Dogway/Avisynth-Scripts/blob/aebb92df33fc912d4ee78000c6db34704d1fc995/TransformsPack%20-%20Models.avsi#L2048) in the implementation, and made a [function](https://github.com/Dogway/Avisynth-Scripts/blob/aebb92df33fc912d4ee78000c6db34704d1fc995/TransformsPack%20-%20Models.avsi#L2083) for 'distance' and 'limit' derivation with the changes stated above and using CAT16 instead. Would like to play with your nuke script to observe the coefficient changes in respect to the primaries.

Will also check your "Michaelis-Menten Constrained" tonescale function, looks very interesting, and see if that makes a difference to my current go-to Hable tonemapper.

Top notch work, congrats.
